name: Scheduled Write EDI Batch Invocation

on:
  schedule:
    # run every 15 mins (starting from 10 after each hour)
    - cron:  '10/15 * * * *'

jobs:
  run_batch_invocation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"
      - run: npm ci
        # run batch-invoke with loopCount=1 (will write one document for each txn set to bucket)
      - run: npm run batch-invoke 1
        env:
          STEDI_API_KEY: ${{secrets.STEDI_API_KEY}}
